title: Orbville
baseURL: /
params:
  accent_color: yellow
  color_scheme: dark
  footer:
    content: '&copy; Orbville. All rights reserved.'
    has_social: true
    links:
      - new_window: true
        text: Made with Stackbit
        url: 'https://www.stackbit.com'
  header:
    has_nav: true
    title: Orbville
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
